name: StaffNotes
version: 0.2
api-version: '1.20'
main: com.staffnotes.StaffNotes

commands:
  notes:
    description: My notes command
    usage: /notes <add | get | remove | help> <playername> <notetype> <note>

permissions:
  notes.default:
    description: Default permission without which the command will not respond
    default: op
  notes.add:
    description: Allows player to add notes to the database
    default: op
  notes.remove:
    description: Allows player to remove notes from the database
    default: op
  notes.view:
    description: Allows player to query and view notes in the database
    default: op
  notes.view.all:
    description: Allows player to query all notes with no other qualifiers /notes Get All
    default: op